export const household_service = [
  "Electrician",
  "Plumber",
  "Wall Painter",
  "Wi-Fi Provider",
  "Carpenter",
  "Gardener/Landscaper",
  "House Cleaner",
  "Pest Control Specialist",
  "HVAC Technician (Heating, Ventilation, and Air Conditioning)",
  "Handyman",
  "Roofer",
  "Flooring Specialist",
  "Window Cleaner",
  "Security System Installer",
  "Appliance Repair Technician",
  "Interior Designer",
  "Pool Maintenance Specialist",
  "Mason/Bricklayer",
  "General Contractor",
  "Locksmith",
];

export const  freelance_service = [
  "Graphic Designer",
  "Web Developer",
  "Poster Maker",
  "Content Writer",
  "Copywriter",
  "SEO Specialist",
  "Social Media Manager",
  "Photographer",
  "Videographer",
  "Video Editor",
  "Illustrator",
  "UI/UX Designer",
  "Animator",
  "Voice-over Artist",
  "Translator",
  "Proofreader/Editor",
  "Digital Marketer",
  "App Developer",
  "Branding Consultant",
  "Email Marketer",
  "Virtual Assistant",
  "Data Analyst",
  "Business Consultant",
  "E-commerce Specialist",
  "3D Modeler",
  "Online Tutor",
  "Blogger",
  "Podcast Editor",
  "Event Planner",
  "Legal Consultant",
  "Financial Advisor",
  "Tax Consultant",
  "Public Relations Specialist",
  "Sales Consultant",
  "Project Manager",
  "IT Support Specialist",
  "CRM Specialist (Customer Relationship Management)",
  "Network Administrator",
  "Technical Writer",
  "Health and Wellness Coach",
  "Fitness Trainer",
  "Nutritionist",
  "Life Coach",
  "Career Coach",
  "Market Research Analyst",
  "Online Store Manager",
  "Supply Chain Consultant",
  "Human Resources Consultant",
  "Recruiter",
  "Customer Service Representative",
  "Transcriptionist",
  "Resume Writer",
  "Grant Writer",
  "Fundraising Consultant",
  "Real Estate Consultant",
  "Interior Decorator",
  "Music Producer",
  "Sound Engineer",
  "Voice Coach",
  "Research Assistant",
];
